### ISSUE TITLE
Token Selector in Form?

### ISSUE THREAD

**Issue by lquessenberry** [spotzero/wsdata#13]
![Let's put a token selector in here](https://puu.sh/yGkji/14ddbc829f.png)

Let's put a token selector in here.

**Comment by morinluc0** [comment]
I have created a new branch and added this functionality into it. 

Going forward I will work on fixing an issue in a separate branch and then merge it into the 8.x-1.x-alpha4 branch where you should be able to test. This way I can submit one slightly larger merge to Dave when everything is ready for the next release posted to D.O

**Comment by morinluc0** [comment]
Token selector was merged in.
