### ISSUE TITLE
Notice: Undefined index: headers_count in 

### ISSUE THREAD

**Issue by lquessenberry** [spotzero/wsdata#17]
Notice: Undefined index: headers_count in Drupal\wsdata\Plugin\WSConnector\WSConnectorSimpleHTTP->getOptionsForm() (line 122 of modules/custom/wsdata/src/Plugin/WSConnector/WSConnectorSimpleHTTP.php).
Drupal\wsdata\Plugin\WSConnector\WSConnectorSimpleHTTP->getOptionsForm(Array) (Line: 191)
Drupal\wsdata\Entity\WSCall->getOptionsForm(NULL, Array) (Line: 119)
Drupal\wsdata\Form\WSCallForm->form(Array, Object) (Line: 117)
Drupal\Core\Entity\EntityForm->buildForm(Array, Object)
call_user_func_array(Array, Array) (Line: 514)
Drupal\Core\Form\FormBuilder->retrieveForm('wscall_edit_form', Object) (Line: 271)
Drupal\Core\Form\FormBuilder->buildForm('wscall_edit_form', Object) (Line: 74)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 576)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
call_user_func_array(Object, Array) (Line: 153)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 657)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by morinluc0** [comment]
After I re worked the form the headers should be getting set properly now.
