### ISSUE TITLE
Notice: Undefined index: headers in Drupal\wsdata\Plugin\WSConnectorBase->saveOptions()

### ISSUE THREAD

**Issue by lquessenberry** [spotzero/wsdata#19]
Possibly related to #17 

Notice: Undefined index: headers in Drupal\wsdata\Plugin\WSConnectorBase->saveOptions() (line 166 of modules/custom/wsdata/src/Plugin/WSConnectorBase.php).
Drupal\wsdata\Plugin\WSConnectorBase->saveOptions(Array) (Line: 84)
Drupal\wsdata\Plugin\WSConnector\WSConnectorSimpleHTTP->saveOptions(Array) (Line: 169)
Drupal\wsdata\Entity\WSCall->setOptions(Array) (Line: 190)
Drupal\wsdata\Form\WSCallForm->save(Array, Object)
call_user_func_array(Array, Array) (Line: 111)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 51)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 585)
Drupal\Core\Form\FormBuilder->processForm('wscall_edit_form', Array, Object) (Line: 314)
Drupal\Core\Form\FormBuilder->buildForm('wscall_edit_form', Object) (Line: 74)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 576)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
call_user_func_array(Object, Array) (Line: 153)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 657)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by morinluc0** [comment]
Similar to issue #17 the form has been re worked so that this issue should not come back.
