### ISSUE TITLE
bug - kint is a required module

### ISSUE THREAD

**Issue by finalhow** [spotzero/wsdata#25]
when using debug mode, the ksm() function is unavailable if the 'kint' module is not enabled... It might need to be listed as  a requirement.

PHP Fatal error:  Call to undefined function Drupal\\wsdata\\Plugin\\WSConnector\\ksm() in /var/www/html/drupal/modules/wsdata/src/Plugin/WSConnector/WSConnectorSimpleHTTP.php on line 214, referer: http://127.0.0.1:8080/admin/structure/wscall/voterview_test_call

This affects branch 8.x.1.x

**Comment by morinluc0** [comment]
Changed the required module in the debug mode so that the error is not produced.
