### ISSUE TITLE
bug - plugin.manager.wsfieldconfig

### ISSUE THREAD

**Issue by finalhow** [spotzero/wsdata#26]
The following error occurs when adding a new wsdata field.  This occurs on version 8.x-1.0-alpha3; note that updating to the latest dev version did solve the error for me.  

[php7:notice] [pid 23094] [client xx.xx.xx.xx:45714] Uncaught PHP Exception Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException: "You have requested a non-existent service "plugin.manager.wsfieldconfig". Did you mean one of these: "plugin.manager.field.widget", "plugin.manager.wsencoder", "plugin.manager.wsdecoder"?" at /var/www/html/dev/dev-configuration-wsdata/web/core/lib/Drupal/Component/DependencyInjection/Container.php line 151, referer: https://dev-configuration-wsdata.xxxx.xxxx.ca/admin/structure/types/manage/street_addresses/fields/add-wsfield

**Comment by morinluc0** [comment]
Found the issue and merged the issue into the 8.x-1.x branch, waiting to push changes to drupal.org
