### ISSUE TITLE
wsdata blocks can't be placed

### ISSUE THREAD

**Issue by lquessenberry** [spotzero/wsdata#3]
I love the idea of what this is intended to do but I can't seem to place it in the blocks layout. It just spins the loading icon and does nothing at the moment.

**Comment by morinluc0** [comment]
@lquessenberry I found the issue, for some reason the form_state is now returning a subFormStateInterface instead of a formStateInterface

I am creating a merge to fix that issue.

**Comment by spotzero** [comment]
I've merged in the changes.
