### ISSUE TITLE
What is the long text field called "Data" used for?

### ISSUE THREAD

**Issue by lquessenberry** [spotzero/wsdata#4]
https://puu.sh/yDOJx/594a15d7cb.png

**Comment by morinluc0** [comment]
We tried to keep the syntax not specific to a specific connector. 

That field is used to pass in a body of a POST request when using the simpleHTTP connector. 
The data field will also be used if you are writing to a file using the LocalFile connector.

**Comment by lquessenberry** [comment]
Excellent. Do you have some examples? I would like to write a brief description and help documentation for it.

**Comment by morinluc0** [comment]
I have created some basic example docs for another person that we may try to re purpose,

**Comment by morinluc0** [comment]
#22 example doc should help better explain the field and how they are used.
