### ISSUE TITLE
In Drupal 8 There's No REST Client Debugger Thingamabob Like D7

### ISSUE THREAD

**Issue by lquessenberry** [spotzero/wsdata#7]
I am over here crying because I don't how to debug things like I did in D7 with wsdata and restclient modules. Is that a thing that can happen?

**Comment by morinluc0** [comment]
Let's create a feature request for a debug mode. I can see how that would be useful.

**Comment by morinluc0** [comment]
@lquessenberry I created a branch for a starting point, so far I created the admin page to set the debug mode.

**Comment by lquessenberry** [comment]
Excellent. I am only familiar with how the old one in D7 worked and I am a terrible programmer, but I can do my best to break things.

**Comment by morinluc0** [comment]
I finished a pretty basic debug mode that will display a debug array with the options send to the connector. 

https://github.com/spotzero/wsdata/tree/7-debug-mode

**Comment by lquessenberry** [comment]
How do I enable this?

**Comment by lquessenberry** [comment]
I believe I have pulled this commit down, but I can't seem to figure out where to look for the debugger.

**Comment by lquessenberry** [comment]
Nevermind i see the config for it.

**Comment by morinluc0** [comment]
Wsdata debugger has been created.
